name: cmake_ubuntu_24

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    branches:
      - '*'

jobs:
  ubuntu-24:
    name: ubuntu-24
    uses: ./.github/workflows/cmake_ubuntu_template.yml
    with:
      os: ubuntu-24.04