name: ros2_workspace_ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  colcon-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            ros_distro: humble
          - os: ubuntu-24.04
            ros_distro: jazzy

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ws/src/rmagine

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}

      - name: Install colcon, rosdep, and vcstool
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-colcon-common-extensions python3-rosdep python3-vcstool

      - name: Import source dependencies
        shell: bash
        run: |
          set -euxo pipefail
          cd ws
          vcs import src --input src/rmagine/source_dependencies.yaml

      - name: Resolve package dependencies
        shell: bash
        run: |
          set -euxo pipefail
          sudo rosdep init || true
          rosdep update --rosdistro "${{ matrix.ros_distro }}"
          cd ws
          rosdep install --from-paths src --ignore-src --rosdistro "${{ matrix.ros_distro }}" -y

      - name: Build package in ROS 2 workspace
        shell: bash
        run: |
          set -euxo pipefail
          source "/opt/ros/${{ matrix.ros_distro }}/setup.bash"
          cd ws
          colcon build \
            --event-handlers console_direct+ \
            --packages-select rmagine
